### ISSUE TITLE
Render was called before OnMount

### ISSUE THREAD

**Issue by lunny** [murlokswarm/app#18]
I think `OnMount` should be called once on `app.Mount` called and before `Render`. And I think document the sequence of events is very useful.

**Comment by maxence-charriere** [comment]
Hi @lunny.
There is no ```app.Mount```
Mount is the action to mount a component into a context (e.g. a window or a menu).
Render is to indicate that a component is modified and should be rendered.

When ```OnMount``` is defined in a component, it is called once when the component is mounted.

The 2 trigger for ```OnMount``` are:
- when calling [context].Mount.
- When ```Render``` is called and a component is created on the fly.
```go
type Foo struct {
    DisplayBar bool
}

(c *Foo) OnMount() {
    fmt.Println("Foo is mounted")
}

(c *Foo) Render() string {
    return `
<div>
    {{if . DisplayBar}}
    <Bar />
    {{else}}
    <p>Bar</p>
    {{end}}
</div>
    `
}
```
```go
type Bar struct {
}

(c *Bar) OnMount() {
    fmt.Println("Bar is mounted")
}

(c *Bar) Render() string {
    return `<p>Bar</p>`
}
```
```go
foo := &Foo{}
win := app.NewWindow(app.Window{
			Title:          "Foo",
			Width:          1280,
			Height:         720,
		})

win.Mount(foo) // foo.OnMount is called. bar doesn't exists yet.
foo.DisplayBar = true // modification of foo.
app.Render(foo) // rerendering foo -> new sub component bar is mounted -> bar.OnMount is called.
```

I think ```app.Render``` should have a better description and have a better coverage in the wiki. There is obviously not enough info about it.
Thanks for highlighting this.

**Comment by maxence-charriere** [comment]
I updated the documentation.
Also you can have more info about how the things works here:
https://github.com/murlokswarm/app/wiki/Component

**Comment by maxence-charriere** [comment]
@lunny, what about this one ?

**Comment by lunny** [comment]
```
type Bar struct {
}

(c *Bar) OnMount() {
    fmt.Println("OnMount ...")
}

(c *Bar) Render() string {
fmt.Println("Render ...")
    return `<p>Bar</p>`
}
```

```
win.Mount(&Bar{})
```
when I call this, then I will get
```
Render ...
OnMount ...
```
but I think it should be
```
OnMount ...
Render ...
```

**Comment by lunny** [comment]
The `OnMount` should be called before all the `Render`?

**Comment by maxence-charriere** [comment]
No because its render which trigger the 2 mount. Under the hood the step are: 
- app.render
- markup.Sync
- detect that there is bar
- mount bar (step done in markup package)
- sync finish and return all the html element to be updated
- app.render send the sync result to the mac driver wchich put it in the webview.

app.render is the action to push a rendering. The real rendering is done after markup.Sync which is called before the rendering in the webview.

**Comment by maxence-charriere** [comment]
@lunny Just updated the previous comment to better reflect how it works.

**Comment by maxence-charriere** [comment]
If you refer to the order within the markup package, the action to mount refers to transform HTML to a go struct tree in order to work on it.
If the html parsing fails, it means that the component is not valid and I don't want to consider a non valid component as mounted.

In markup render refers to "rendering a valid html piece of code".
Which is what a component Render method does.
This render is effectively done before mount.

In the other side, there is the rendering which is done in a web view, which consist to render the HTML on the screen.
This one happens after a component is mounted.

**Comment by maxence-charriere** [comment]
Hey @lunny how is going with this one?

**Comment by lunny** [comment]
OK. I see. I think it's just need be documented.
