### ISSUE TITLE
onchange confusion

### ISSUE THREAD

**Issue by jcloutz** [murlokswarm/app#27]
I've been playing with the sample app and it seems like the `onchange` event should fire each time the input field changes value not when enter is pressed. Would it make more sense to have an `onsubmit`or `onconfirm` event?

This is the awesome project, i'm looking forward to watching it evolve :)

**Comment by maxence-charriere** [comment]
on change refers to the HTML event. The package just map it to a Go function rather than a Javascript one. 
Free for you to use the best one suited for your case :).

**Comment by jcloutz** [comment]
Next question then :) If the onchange event only fires when the enter key is pressed like in html is it possible to access the underlying DOM and get the value of an input?

For example if I wanted to have have a markdown editor with a live view side by side, similar to this, https://jbt.github.io/markdown-editor/, how could I do that? I see how to use a keyboard events and such but that doesn't provide the value of the input, only the key properties. Am I just not seeing how to programmatically get the input value without using the change events `arg.Value`?

**Comment by maxence-charriere** [comment]
This is not possible yet.
It is planned to add some way to interact with the dom.

For the moment you can just use one of the app argument to get some event values:
- https://godoc.org/github.com/murlokswarm/app#KeyboardArg
- https://godoc.org/github.com/murlokswarm/app#MouseArg
- https://godoc.org/github.com/murlokswarm/app#ChangeArg
- https://godoc.org/github.com/murlokswarm/app#WheelArg

just put it as the first argument of the Go callback and what is corresponding to a js event will be mapped.

```go
func (c *Component) OnChange(arg app.ChangeArg) {
}
```

**Comment by maxence-charriere** [comment]
Looks like i gonna have to implement that sooner that I thought.
Looks pretty essential!
Thanks for the feedback.

**Comment by jcloutz** [comment]
Is there anyway to bind the html `id` property? this would make it infinitely easier to handle forms.

**Comment by maxence-charriere** [comment]
do you  have an exemple of what you try to do ?

**Comment by jcloutz** [comment]
Nothing specific, I guess it's more of a question of how to process a form. There needs to be a way to get the value from multiple inputs on the page. I'm just sure of the best way to go about it. Is it possible to bind a variable in the component to a specific id in on the page? Possibly a struct representing the form?

```go
type Form struct {
	FirstName string
	LastName string
	Services []string
	Phones []struct {
		Number string
	}
}
```

```html
<form>
	<div id="app">
		<div>
			<label>First Name</label>
			<input type="text" id="first_name" placeholder="First Name"/>
		</div>
		<div>
			<label>Last Name</label>
			<input type="text" id="last_name" placeholder="Last Name"/>
		</div>

		<div>
			<label>Services</label>
			<select multiple id="categories">
				<option>Service 1</option>	
				<option>Service 2</option>
				<option>Service 3</option>
			</select>
		</div>

		<label>Phone Numbers</label>
		<ul>
			<li>
				<input type="text" id="phones[0]" value="phones[0]"/>
			</li>
			<li>
				<input type="text" id="phones[1]" value="phones[1]" />
			</li>
		</ul>
		<button type="button" onclick="addPhone()">Add Phone Number</button>
	</div>

	<button type="submit" onsubmit="processForm()">Submit</button>
<form>
```

**Comment by maxence-charriere** [comment]
I see.
You could set the ```onchange``` event on every input.
But, this is pretty heavy...

Something cool would be if you can also point a component field rather than only a function.
The app package would have to be smart enough to call a function or a mapping but it looks pretty feasible and go in the continuity of what is already done.

```go
type Form struct {
	FirstName string
	LastName  string
}

func (f *Form) Render() string {
	return `
<div>
	<input type="text" placeholder="First Name" onchange="FirstName" />
</div>
    `
}
```

Firstname is a field of the ```Form``` struct.
The value passed to the onchange event would be directly mapped into ```FirstName```field.

What do you think about it ?

**Comment by jcloutz** [comment]
Using `onchange` to bind to a struct field may be a bit confusing if it can refer to either a field or a method call. What about using custom html attributes similar to Angular's `ng-model` or Vue's `v-model`?

**Comment by maxence-charriere** [comment]
The problem with the custom attribute is that it doesn't trigger anything. We would have to find a way to watch events and check the difference with the current state which mean:
- more complicated communication between the web view and Go.
- Have to set javascript event handlers and make sure they persist even when a node is fully replaced.
- more complexity in the javascript code (which I hardly try to avoid).

Beside, I dont have the feeling that pointing to a field would be confusing.
In Go, struct element names are always unique and refers to a field or a function.
No mistake could be done by referring to a func or a field because they never collide.

The current behavior unmarshal an event arg into the first argument of a Go func.
It's already smart enough to do nothing if the Go func doesn't have an argument.
It could also be smart enough to unmarshal the event arg into a field value.

With good documentation and the adequate warning when something points to nothing, I really have the feeling that would works.

**Comment by maxence-charriere** [comment]
@jcloutz 
You can also get the input value from a key event now.
https://github.com/murlokswarm/app/commit/faa5b513b6754713e08eeeb5994af22e62792f7e

**Comment by jcloutz** [comment]
@maxence-charriere awesome!

**Comment by maxence-charriere** [comment]
Hey @jcloutz.
Just pushed the modifications to map the event to a field.
I gonna close this issue.
Feel free to reopen if you need more things or open another one.

Thank you very much for the feedbacks.
