### ISSUE TITLE
Running in a browser

### ISSUE THREAD

**Issue by mochacoder** [murlokswarm/app#30]
It looks like the project is made specifically for native deployments, I'm wondering if it's feasible to support web deployments as well even if it's limited in which browsers would be supported. Would this be possible using something like gopherjs to run the go code in the browser?

**Comment by maxence-charriere** [comment]
I have no idea for gopher.js. Looks not impossible but I can't tell. I would need to try it to see its limits.

Another idea would be to have a driver that implement a bridge using javascript and a web socket.
The flaw with this approach is that a lot of thing is done on the server side (the go part) and this website would be pretty dependent to a good connection to be responsive.

**Comment by joeblew99** [comment]
i know that running murlok in a web browser is being worked on over here:
https://github.com/gu-io/gu/tree/feature/apps

It is a bridge, just like @maxence-charriere  suggested.

The docs do not directly talk about murlok, but me and the GU developer have specifically discussed this as a use case. The reason this makes sense is because GU allows running a web app where all rendering happens in the backend, which matches what murlok does. 
GU also allows compiling using gopherjs so it runs in a browser too.

I have to warn you though thats its early days on this. 
i just wanted to let you know.

**Comment by influx6** [comment]
Ya, unfortunately the gopherjs driver am building is very specific to the architecture I built for Gu. But modifying it to fit murlock *App instances should be possible with some mental logic changes by @maxence-charriere.

Gu currently works with gopherjs on the `master` branch. But the changes in `features/apps` should change that and allow more other means of rendering the application built.

@joeblew99 Is building a means to have murlock work with the go bindings for QT, so that might be something to look forward to as well.

**Comment by maxence-charriere** [comment]
Hey guys, I'm pretty close to achieve this:
<img width="2032" alt="screen shot 2018-03-01 at 1 40 18 am" src="https://user-images.githubusercontent.com/2692731/36837553-8fa21c96-1cf1-11e8-9751-6e0943bd3d1a.png">

I have a problem though,
I need to call a function generated by gopherjs from javascript.
Did not find any documentation about it :(

@influx6 @joeblew99 , I saw you deal with gopherjs in gu, have you any hint about it?

**Comment by maxence-charriere** [comment]
Omg... I did it!

<img width="2032" alt="screen shot 2018-03-01 at 2 53 20 am" src="https://user-images.githubusercontent.com/2692731/36841103-230d57e8-1cfc-11e8-8b24-830e524265a9.png">

**Comment by maxence-charriere** [comment]
This is up.
See [hello example](https://github.com/murlokswarm/app/tree/master/examples/hello) and [nav example](https://github.com/murlokswarm/app/tree/master/examples/nav) to see how this works.
