### ISSUE TITLE
DOMElement  is incomplete

### ISSUE THREAD

**Issue by themihai** [murlokswarm/app#45]
A [dom elemen](https://godoc.org/github.com/murlokswarm/app#DOMElement)t has sets/slices of attributes not just one. An attribute can have different keys than "id",  "class" and value" (e.g. data-xyz, hidden, label etc..) along with other properties.

  I would propose to bring it more in line with [x/html](godoc.org/golang.org/x/net/html) to better represent the structure of a html node. We may exclude the relationships (`Parent, FirstChild, LastChild, PrevSibling, NextSibling *Node)` if  murlokswarm is not interested to serialize the html(though I think it would be quite handy). 

```

type Node struct {
    Parent, FirstChild, LastChild, PrevSibling, NextSibling *Node
    Type      NodeType
    DataAtom  atom.Atom
    Data      string
    Namespace string
    Attr      []Attribute
}

type Attribute struct {
    Namespace, Key, Val string
}
```

**Comment by maxence-charriere** [comment]
This is a bunch of javascript to handle and it's pretty tricky to serialize dom objects.
I have got some very strange results when i was just trying to JSON.stringify the attributes in order to have a full attribute map.

Right know, I prefer to focus on other things.
But if someone is open to clone this and try to make it, would be glad to review the changes.

**Comment by themihai** [comment]
Did you consider the Objective-C API instead of JS? 
https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/DisplayWebContent/Tasks/DOMObjCBindings.html
